# PERSONALIZATION
# Site variables
name: HackCU Team
og: assets/img/og.png
logo: assets/img/logo.png
original_repo: https://github.com/hackcu/events
description: Info on how to be part of the HackCU team
ga: UA-109088240-1
domain: team.hackcu.org


# Style variables
accent_color: "#22b573"
events_overlay_color: "#2697FF"
background_color: "#FAFAFA"
footer_text_color: "#666666"

# Author variables
author: HackCU
mission: "Bring people together to create, learn, and have fun!"
story: "HackCU began four years ago when a group of passionate students wanted to provide other students
   the time and space to express their crativity and work on things they usually don't get a chance to.
   Since then we’ve been committed to fulfilling our mission of bringing students high-quality, inclusive
   events open to everyone irrespective of their experience."
team-description: "Our team comprises of innovative self starters who constantly want to empower the community.
    From computer scientists to entrepeneurs, our team has people of all backgrounds and experiences. An important
    element of HackCU is that all of our events are led exclusively by students. We teach and learn from our team
    members how to run and manage some of the largest technology events in the country. With this experience, our
    team members and alumni go on to work for some of the biggest names in tech and some even start their own companies."
companies-description: "HackCU helps set up its team members for great careers in technology. We pride ourselves on teaching 
    our team members how to be great employees and founders. Below is a list of some of the companies our team members and alumni
    have gone on to intern at, work for, or found."
email: contact@hackcu.org

# Social media + community variables
twitter: hackcu
fb: hackcu
fb-community: hackcu
slack-signup: https://slack.hackcu.org

instagram: hackcu
github-org: hackcu
 
# Internal configuration
sass:
    sass_dir: assets/_sass
    style: compressed